export const Questions = [
	{
		prompt: "1. İnek",
		optionA: "Shark",
		optionB: "Lion",
		optionC: "Crow",
		optionD: "Cow",
		answer: "optionD",
	},
	{
		prompt: "2. Yunus",
		optionA: "Tiger",
		optionB: "Bird",
		optionC: "Dolphin",
		optionD: "Octopus",
		answer: "optionC",
	},
	{
		prompt: "3. Kaplan",
		optionA: "tiger",
		optionB: "cat",
		optionC: "zebra",
		optionD: "parrot",
		answer: "optionA",
	},
	{
		prompt: "4. karga",
		optionA: "cow",
		optionB: "crow",
		optionC: "goat",
		optionD: "sheep",
		answer: "optionB",
	},
	{
		prompt: "5. at",
		optionA: "horse",
		optionB: "bear",
		optionC: "zebra",
		optionD: "pig",
		answer: "optionA",
	},
	{
		prompt: "6. baykuş",
		optionA: "parrot",
		optionB: "eagle",
		optionC: "owl",
		optionD: "seagull",
		answer: "optionC",
	},
	{
		prompt: "7. keçi",
		optionA: "fish",
		optionB: "goat",
		optionC: "shark",
		optionD: "whale",
		answer: "optionB",
	},
	{
		prompt: "8. kartal",
		optionA: "eagle",
		optionB: "snake",
		optionC: "spider",
		optionD: "rabbit",
		answer: "optionA",
	},
	{
		prompt: "9. dil",
		optionA: "teeth",
		optionB: "knees",
		optionC: "toes",
		optionD: "tongue",
		answer: "optionD",
	},
	{
		prompt: "10. diş",
		optionA: "teeth",
		optionB: "nose",
		optionC: "feet",
		optionD: "tongue",
		answer: "optionA",
	},
	{
		prompt: "11. yanak",
		optionA: "chin",
		optionB: "shoulders",
		optionC: "cheeks",
		optionD: "eyes",
		answer: "optionC",
	},
	{
		prompt: "12. Eyes, ears, nose and ………………..are on the face.",
		optionA: "mouth",
		optionB: "elbow",
		optionC: "leg",
		optionD: "knee",
		answer: "optionA",
	},
	{
		prompt: "13. People have only one ……………… and only one ……………………",
		optionA: "eye-ear",
		optionB: "nose- eye",
		optionC: "nose-mouth",
		optionD: "shoulder-arm",
		answer: "optionC",
	},
	{
		prompt: "14. People have two………………",
		optionA: "foots",
		optionB: "feet",
		optionC: "heads",
		optionD: "noses",
		answer: "optionB",
	},
	{
		prompt: "15. People have two………………",
		optionA: "bodies",
		optionB: "eyes",
		optionC: "noses",
		optionD: "toes",
		answer: "optionB",
	},
	{
		prompt: "16. People have two………………",
		optionA: "mouths",
		optionB: "noses",
		optionC: "ears",
		optionD: "bodies",
		answer: "optionC",
	},
	{
		prompt: "17. People have ten ………………..",
		optionA: "shoulders",
		optionB: "eyes",
		optionC: "noses",
		optionD: "fingers",
		answer: "optionD",
	},
	{
		prompt: "18. böğürtlen",
		optionA: "blackberries",
		optionB: "strawberries",
		optionC: "cereal",
		optionD: "soybeans",
		answer: "optionA",
	},
	{
		prompt: "19. yağ",
		optionA: "pancake",
		optionB: "blackberries",
		optionC: "butter",
		optionD: "cucumber",
		answer: "optionC",
	},
	{
		prompt: "20. salata",
		optionA: "cucumber",
		optionB: "pepper",
		optionC: "banana",
		optionD: "kiwi",
		answer: "optionA",
	},
	{
		prompt: "21. zeytin",
		optionA: "beans",
		optionB: "soybeans",
		optionC: "peas",
		optionD: "olives",
		answer: "optionD",
	},
	{
		prompt: "22. 44",
		optionA: "forty",
		optionB: "forty-four",
		optionC: "fourteen",
		optionD: "four",
		answer: "optionB",
	},
	{
		prompt: "23. 13",
		optionA: "thirteen",
		optionB: "threeteen",
		optionC: "thirty",
		optionD: "thirty-three",
		answer: "optionA",
	},
	{
		prompt: "24. 57",
		optionA: "seventy-five",
		optionB: "fifty-six",
		optionC: "fifty-eight",
		optionD: "fifty-seven",
		answer: "optionD",
	},
	{
		prompt: "25. 21",
		optionA: "twelve",
		optionB: "twenty",
		optionC: "twenty-one",
		optionD: "thirty-one",
		answer: "optionC",
	},
	{
		prompt: "26. 98",
		optionA: "ninety-eight",
		optionB: "eighty-eight",
		optionC: "eighty-nine",
		optionD: "nineteen",
		answer: "optionA",
	},
	{
		prompt: "27. 15",
		optionA: "fiveteen",
		optionB: "fifteen",
		optionC: "fifty",
		optionD: "five",
		answer: "optionB",
	},
	{
		prompt: "28. 20",
		optionA: "twelve",
		optionB: "two",
		optionC: "twenty-two",
		optionD: "twenty",
		answer: "optionD",
	},
	{
		prompt: "29. 12",
		optionA: "twenty",
		optionB: "twoteen",
		optionC: "twelve",
		optionD: "thirty",
		answer: "optionC",
	},
	{
		prompt: "30. 34",
		optionA: "thirty-four",
		optionB: "forty-four",
		optionC: "forty-three",
		optionD: "three-four",
		answer: "optionA",
	},
	{
		prompt: "31. 100",
		optionA: "one thousand",
		optionB: "one hundred",
		optionC: "ten",
		optionD: "ninety-nine",
		answer: "optionB",
	},
	{
		prompt: "32. tavuk",
		optionA: "duck",
		optionB: "chicken",
		optionC: "turtle",
		optionD: "rabbit",
		answer: "optionB",
	},
	{
		prompt: "33. ördek",
		optionA: "duck",
		optionB: "bug",
		optionC: "rooster",
		optionD: "ant",
		answer: "optionA",
	},
	{
		prompt: "34. ……………. have wings.",
		optionA: "dogs",
		optionB: "cats",
		optionC: "ladybugs",
		optionD: "turtles",
		answer: "optionC",
	},
	{
		prompt: "35. ……………… can speak.",
		optionA: "cats",
		optionB: "parrots",
		optionC: "rabbits",
		optionD: "hamsters",
		answer: "optionB",
	},
	{
		prompt: "36. ………………. have feathers.",
		optionA: "birds",
		optionB: "horses",
		optionC: "dogs",
		optionD: "cats",
		answer: "optionA",
	},
	{
		prompt: "37. …………………. don’t have fur.",
		optionA: "turtles",
		optionB: "tigers",
		optionC: "lions",
		optionD: "horses",
		answer: "optionA",
	},
	{
		prompt: "38. akordiyon",
		optionA: "piano",
		optionB: "organ",
		optionC: "accordion",
		optionD: "keyboard",
		answer: "optionC",
	},
	{
		prompt: "39. klarnet",
		optionA: "clarinet",
		optionB: "cymbal",
		optionC: "harp",
		optionD: "guitar",
		answer: "optionA",
	},
	{
		prompt: "40. mızıka",
		optionA: "melodica",
		optionB: "harp",
		optionC: "cymbal",
		optionD: "harmonica",
		answer: "optionA",
	},
	{
		prompt: "41. ………………….is the closest planet to the Sun.",
		optionA: "Neptune",
		optionB: "Earth",
		optionC: "Mercury",
		optionD: "Mars",
		answer: "optionC",
	},
	{
		prompt: "42. …………………….is the farthest planet from the Sun.",
		optionA: "Mercury",
		optionB: "Uranus",
		optionC: "The Moon",
		optionD: "Neptune",
		answer: "optionD",
	},
	{
		prompt: "43. Mars is also known as ………………………………",
		optionA: "the largest planet",
		optionB: "Red Planet",
		optionC: "Black Planet",
		optionD: "Gray Planet",
		answer: "optionB",
	},
	{
		prompt: "44. Our galaxy is called …………………….",
		optionA: "Asteroid",
		optionB: "Milky Way",
		optionC: "Red Planet",
		optionD: "Satellite",
		answer: "optionB",
	},
	{
		prompt: "45. The Moon is the Earth’s ………………….",
		optionA: "planet",
		optionB: "sun",
		optionC: "satellite",
		optionD: "comet",
		answer: "optionC",
	},
	{
		prompt: "46. kuyruklu yıldız",
		optionA: "the Sun",
		optionB: "planet",
		optionC: "the Moon",
		optionD: "comet",
		answer: "optionD",
	},
	{
		prompt: "47. …………….. is the largest planet in our solar system.",
		optionA: "Mercury",
		optionB: "Jupiter",
		optionC: "Pluto",
		optionD: "Venus",
		answer: "optionB",
	},
	{
		prompt: "48. balta",
		optionA: "hammer",
		optionB: "screw",
		optionC: "screwdriver",
		optionD: "axe",
		answer: "optionD",
	},
	{
		prompt: "49. çekiç",
		optionA: "axe",
		optionB: "hammer",
		optionC: "bolt",
		optionD: "wrench",
		answer: "hammer",
	},
	{
		prompt: "50. boya fırçası",
		optionA: "paint brush",
		optionB: "paint can",
		optionC: "toolbox",
		optionD: "hammer",
		answer: "optionA",
	},
	{
		prompt: "51. testere",
		optionA: "knife",
		optionB: "wrench",
		optionC: "saw",
		optionD: "tape measure",
		answer: "optionC",
	},
	{
		prompt: "52. tornavida",
		optionA: "nail",
		optionB: "axe",
		optionC: "scalpel",
		optionD: "screwdriver",
		answer: "optionD",
	},
	{
		prompt: "53. vida",
		optionA: "nail",
		optionB: "screw",
		optionC: "paint roller",
		optionD: "drill",
		answer: "optionB",
	},
	{
		prompt: "54. matkap",
		optionA: "screwdriver",
		optionB: "wrench",
		optionC: "drill",
		optionD: "hammer",
		answer: "optionC",
	},
	{
		prompt: "55. klavye",
		optionA: "keyboard",
		optionB: "mouse",
		optionC: "browser",
		optionD: "website",
		answer: "optionA",
	},
	{
		prompt: "56. fare",
		optionA: "keyboard",
		optionB: "application",
		optionC: "mouse",
		optionD: "browser",
		answer: "optionC",
	},
	{
		prompt: "57. uygulama",
		optionA: "password",
		optionB: "application",
		optionC: "username",
		optionD: "connection",
		answer: "optionB",
	},
	{
		prompt: "58. tarayıcı",
		optionA: "file",
		optionB: "laptop",
		optionC: "desktop",
		optionD: "browser",
		answer: "optionD",
	},
	{
		prompt: "59. dosya",
		optionA: "application",
		optionB: "file",
		optionC: "website",
		optionD: "personal computer",
		answer: "optionB",
	},
	{
		prompt: "60. şifre",
		optionA: "password",
		optionB: "screen",
		optionC: "desktop",
		optionD: "hard disk drive",
		answer: "optionA",
	},
	{
		prompt: "62. January - ………….- March",
		optionA: "February",
		optionB: "April",
		optionC: "May",
		optionD: "July",
		answer: "optionA",
	},
	{
		prompt: "63. September-………………-November",
		optionA: "December",
		optionB: "June",
		optionC: "October",
		optionD: "August",
		answer: "optionC",
	},
	{
		prompt: "63. June– ………………– ……………..",
		optionA: "March - April",
		optionB: "August - September",
		optionC: "February - March",
		optionD: "July - August",
		answer: "optionD",
	},
	{
		prompt: "64. January is in the ……………..",
		optionA: "summer",
		optionB: "winter",
		optionC: "autumn",
		optionD: "spring",
		answer: "optionB",
	},
	{
		prompt: "65. Spring months are ……………, ……………… and …………………",
		optionA: "October, November, December",
		optionB: "January, February, March",
		optionC: "March, April, May",
		optionD: "June , July , August",
		answer: "optionC",
	},
	{
		prompt: "66. Autumn months are ……………, ……………….. and ………………….",
		optionA: "September, October, November",
		optionB: "December, January, February",
		optionC: "August, September, October",
		optionD: "November, December, January",
		answer: "optionA",
	},
	{
		prompt: "67. çiçek",
		optionA: "flower",
		optionB: "animal",
		optionC: "grass",
		optionD: "river",
		answer: "optionA",
	},
	{
		prompt: "68. orman",
		optionA: "lake",
		optionB: "sea",
		optionC: "forest",
		optionD: "mountain",
		answer: "optionC",
	},
	{
		prompt: "69. çimen",
		optionA: "flower",
		optionB: "forest",
		optionC: "animal",
		optionD: "grass",
		answer: "optionD",
	},
	{
		prompt: "70. göl",
		optionA: "ocean",
		optionB: "lake",
		optionC: "sun",
		optionD: "moon",
		answer: "optionB",
	},
	{
		prompt: "71. dağ",
		optionA: "river",
		optionB: "lake",
		optionC: "mountain",
		optionD: "sea",
		answer: "optionC",
	},
	{
		prompt: "72. bitki",
		optionA: "forest",
		optionB: "sand",
		optionC: "ocean",
		optionD: "plant",
		answer: "optionD",
	},
	{
		prompt: "73. nehir",
		optionA: "sea",
		optionB: "river",
		optionC: "flower",
		optionD: "moon",
		answer: "optionB",
	},
	{
		prompt: "74. deniz",
		optionA: "sea",
		optionB: "forest",
		optionC: "animals",
		optionD: "insects",
		answer: "optionA",
	},
	{
		prompt: "75. ağaç",
		optionA: "flower",
		optionB: "grass",
		optionC: "seed",
		optionD: "tree",
		answer: "optionD",
	},
	{
		prompt: "76. hayvanlar",
		optionA: "plants",
		optionB: "animals",
		optionC: "ocean",
		optionD: "mountain",
		answer: "optionB",
	},
	{
		prompt: "77. karınca",
		optionA: "spider",
		optionB: "ladybug",
		optionC: "ant",
		optionD: "cockroach",
		answer: "optionC",
	},
	{
		prompt: "78. arı",
		optionA: "spider",
		optionB: "bee",
		optionC: "butterfly",
		optionD: "mosquito",
		answer: "optionB",
	},
	{
		prompt: "79. hamamböceği",
		optionA: "snail",
		optionB: "ladybug",
		optionC: "spider",
		optionD: "cockroach",
		answer: "optionD",
	},
	{
		prompt: "80. sinek",
		optionA: "fly",
		optionB: "butterfly",
		optionC: "bee",
		optionD: "cockroach",
		answer: "optionA",
	},
	{
		prompt: "81. uğurböceği",
		optionA: "mosquito",
		optionB: "ladybug",
		optionC: "spider",
		optionD: "bee",
		answer: "optionB",
	},
	{
		prompt: "82. sivrisinek",
		optionA: "butterfly",
		optionB: "ladybug",
		optionC: "spider",
		optionD: "mosquito",
		answer: "optionD",
	},
	{
		prompt: "83. örümcek",
		optionA: "beetle",
		optionB: "spider",
		optionC: "ant",
		optionD: "ladybug",
		answer: "optionB",
	},
	{
		prompt: "84. kelebek",
		optionA: "butterfly",
		optionB: "spider",
		optionC: "bee",
		optionD: "ladybug",
		answer: "optionA",
	},
	{
		prompt: "85. kelebek",
		optionA: "butterfly",
		optionB: "spider",
		optionC: "bee",
		optionD: "ladybug",
		answer: "optionA",
	},
	{
		prompt: "86. sisli",
		optionA: "rainy",
		optionB: "foggy",
		optionC: "windy",
		optionD: "stormy",
		answer: "optionB",
	},
	{
		prompt: "87. rüzgarlı",
		optionA: "rainy",
		optionB: "foggy",
		optionC: "windy",
		optionD: "stormy",
		answer: "optionC",
	},
	{
		prompt: "88. yağmurlu",
		optionA: "rainy",
		optionB: "foggy",
		optionC: "windy",
		optionD: "stormy",
		answer: "optionA",
	},
	{
		prompt: "89. yağmurlu",
		optionA: "rainy",
		optionB: "foggy",
		optionC: "windy",
		optionD: "stormy",
		answer: "optionD",
	},
	{
		prompt: "90. yarasa",
		optionA: "bat",
		optionB: "eagle",
		optionC: "crow",
		optionD: "elephant",
		answer: "optionA",
	},
	{
		prompt: "91. ayı",
		optionA: "lion",
		optionB: "jaguar",
		optionC: "bear",
		optionD: "crocodile",
		answer: "optionC",
	},
	{
		prompt: "92. goril",
		optionA: "hippopotamus",
		optionB: "gorilla",
		optionC: "bear",
		optionD: "crocodile",
		answer: "optionB",
	},
	{
		prompt: "93. hipopotam",
		optionA: "hippopotamus",
		optionB: "gorilla",
		optionC: "bear",
		optionD: "crocodile",
		answer: "optionA",
	},
	{
		prompt: "94. kutup ayısı",
		optionA: "hippopotamus",
		optionB: "gorilla",
		optionC: "bear",
		optionD: "polar bear",
		answer: "optionC",
	},
	{
		prompt: "95. yılan",
		optionA: "snake",
		optionB: "gorilla",
		optionC: "bear",
		optionD: "polar bear",
		answer: "optionA",
	},
	{
		prompt: "96. mor",
		optionA: "blue",
		optionB: "pink",
		optionC: "orange",
		optionD: "purple",
		answer: "optionD",
	},
	{
		prompt: "97. sarı",
		optionA: "blue",
		optionB: "pink",
		optionC: "orange",
		optionD: "yellow",
		answer: "optionD",
	},
	{
		prompt: "98. siyah",
		optionA: "blue",
		optionB: "black",
		optionC: "orange",
		optionD: "yellow",
		answer: "optionB",
	},
	{
		prompt: "99. turuncu",
		optionA: "blue",
		optionB: "black",
		optionC: "orange",
		optionD: "yellow",
		answer: "optionC",
	},
	{
		prompt: "100. What color is an orange?",
		optionA: "blue",
		optionB: "black",
		optionC: "orange",
		optionD: "yellow",
		answer: "optionC",
	},
]
